# Generated by Django 5.2.4 on 2025-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_name", models.CharField(max_length=100)),
                (
                    "problem_difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")]
                    ),
                ),
                ("statement", models.TextField(max_length=3000)),
                ("constraints", models.TextField(max_length=500)),
            ],
        ),
    ]
